# Please see the documentation for all configuration options:
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 2
    # For GitHub Actions, you do not need to set the directory to
    # /.github/workflows. Configuring the key to / automatically instructs
    # Dependabot to search the /.github/workflows directory, as well as the
    # action.yml / action.yaml file from the root directory.
    directory: /
    schedule:
      interval: cron
      cronjob: 0 8 5,25 * * # At 08:00, on day 5 and 25 of the month
    cooldown:
      default-days: 5
    groups:
      actions-dependencies:
        update-types: [major, minor, patch]
    labels:
      - ⬆️ Dependencies
