name: Update GitHub README Stats
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 1/2 * *"

jobs:
  generate-stats:
    strategy:
      matrix:
        theme: [light, dark]
    runs-on: ubuntu-latest
    name: Generate stats cards
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate stats-${{ matrix.theme }}
        uses: UlyssesZh/grs-action@master
        id: generate
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&count_private=true&include_all_commits=true&number_format=long&hide_title=true&hide_rank=true&show=discussions_started,prs_merged&hide_border=true&theme=${{ matrix.theme }}
          path: grs/stats-${{ matrix.theme }}.svg
      - name: Upload stats-${{ matrix.theme }}
        uses: actions/upload-artifact@v4
        with:
          name: stats-${{ matrix.theme }}
          path: grs
  generate-langs:
    strategy:
      matrix:
        theme: [light, dark]
    runs-on: ubuntu-latest
    name: Generate top language cards
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate stats-${{ matrix.theme }}
        uses: UlyssesZh/grs-action@master
        id: generate
        with:
          options: username=${{ github.repository_owner }}&layout=donut&langs_count=20&hide_border=true&disable_animations=true&theme=${{ matrix.theme }}
          path: grs/langs-${{ matrix.theme }}.svg
          card: langs
      - name: Upload langs-${{ matrix.theme }}
        uses: actions/upload-artifact@v4
        with:
          name: langs-${{ matrix.theme }}
          path: grs
  push:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    name: Push
    needs: [generate-stats, generate-langs]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: stats-dark
          path: grs
      - uses: actions/download-artifact@v4
        with:
          name: stats-light
          path: grs
      - uses: actions/download-artifact@v4
        with:
          name: langs-dark
          path: grs
      - uses: actions/download-artifact@v4
        with:
          name: langs-light
          path: grs
      - name: Push
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: grs
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
