name: Update GitHub README Stats
on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 1/2 * *
  push:
    branches:
      - master
    paths:
      - .github/workflows/update-readme-stats.yml

concurrency:
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CHECK_PERMISSIONS: 0

permissions: {}

jobs:
  generate-stats:
    strategy:
      matrix:
        theme: [light, dark]
    runs-on: ubuntu-latest
    name: Generate stats cards
    permissions:
      contents: write
    steps:
      - id: check-permissions
        name: Check action permissions
        uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        if: env.CHECK_PERMISSIONS == '1'
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - id: generate-stats-svg
        name: Generate stats-${{ matrix.theme }}
        uses: UlyssesZh/grs-action@7d6d316976be5912ac850de0d88a34364a144d44 # master
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&count_private=true&include_all_commits=true&number_format=long&hide_title=true&hide_rank=true&show=discussions_started,prs_merged&hide_border=true&theme=${{ matrix.theme }}
          path: grs/stats-${{ matrix.theme }}.svg
      - id: upload-stats
        name: Upload stats-${{ matrix.theme }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: stats-${{ matrix.theme }}
          path: grs
  generate-langs:
    permissions:
      contents: write
    strategy:
      matrix:
        theme: [light, dark]
    runs-on: ubuntu-latest
    name: Generate top language cards
    steps:
      - id: check-permissions
        name: Check action permissions
        uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        if: env.CHECK_PERMISSIONS == '1'
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - id: generate-langs-svg
        name: Generate stats-${{ matrix.theme }}
        uses: UlyssesZh/grs-action@7d6d316976be5912ac850de0d88a34364a144d44 # master
        with:
          options: username=${{ github.repository_owner }}&layout=donut&langs_count=20&hide_border=true&disable_animations=true&theme=${{ matrix.theme }}
          path: grs/langs-${{ matrix.theme }}.svg
          card: langs
      - id: upload-langs
        name: Upload langs-${{ matrix.theme }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: langs-${{ matrix.theme }}
          path: grs
  push:
    permissions:
      actions: read
      contents: write
    runs-on: ubuntu-latest
    name: Push images
    needs: [generate-stats, generate-langs]
    steps:
      - id: check-permissions
        name: Check action permissions
        uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        if: env.CHECK_PERMISSIONS == '1'
      - id: download_stats-dark
        name: Download stats (dark)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: stats-dark
          path: grs
      - id: download_stats-light
        name: Download stats (light)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: stats-light
          path: grs
      - id: download_langs-dark
        name: Download langs (dark)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: langs-dark
          path: grs
      - id: download_langs-light
        name: Download langs (light)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: langs-light
          path: grs
      - id: push-images
        name: Push images
        uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865 # v4.2.0
        with:
          target_branch: grs
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
